// Mocks generated by Mockito 5.4.5 from annotations
// in dskk_flutter_refactor/test/features/profile/data/repositories/user_profile_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dskk_flutter_refactor/core/network/network_info.dart' as _i11;
import 'package:dskk_flutter_refactor/features/profile/data/datasources/profile_local_data_source.dart'
    as _i10;
import 'package:dskk_flutter_refactor/features/profile/data/datasources/profile_remote_data_source.dart'
    as _i4;
import 'package:dskk_flutter_refactor/features/profile/data/models/liked_story_dto.dart'
    as _i9;
import 'package:dskk_flutter_refactor/features/profile/data/models/saved_item_dto.dart'
    as _i8;
import 'package:dskk_flutter_refactor/features/profile/data/models/transaction_dto.dart'
    as _i7;
import 'package:dskk_flutter_refactor/features/profile/data/models/user_profile_dto.dart'
    as _i2;
import 'package:dskk_flutter_refactor/features/profile/data/models/wallet_summary_dto.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserProfileDto_0 extends _i1.SmartFake
    implements _i2.UserProfileDto {
  _FakeUserProfileDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWalletSummaryDto_1 extends _i1.SmartFake
    implements _i3.WalletSummaryDto {
  _FakeWalletSummaryDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProfileRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRemoteDataSource extends _i1.Mock
    implements _i4.ProfileRemoteDataSource {
  MockProfileRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserProfileDto> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i5.Future<_i2.UserProfileDto>.value(_FakeUserProfileDto_0(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i2.UserProfileDto>);

  @override
  _i5.Future<_i2.UserProfileDto> updateUserProfile({
    required String? nickName,
    bool? onlineFlag,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserProfile,
          [],
          {
            #nickName: nickName,
            #onlineFlag: onlineFlag,
          },
        ),
        returnValue: _i5.Future<_i2.UserProfileDto>.value(_FakeUserProfileDto_0(
          this,
          Invocation.method(
            #updateUserProfile,
            [],
            {
              #nickName: nickName,
              #onlineFlag: onlineFlag,
            },
          ),
        )),
      ) as _i5.Future<_i2.UserProfileDto>);

  @override
  _i5.Future<String> uploadAvatar({required String? imageFilePath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadAvatar,
          [],
          {#imageFilePath: imageFilePath},
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #uploadAvatar,
            [],
            {#imageFilePath: imageFilePath},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<_i3.WalletSummaryDto> getWalletSummary() => (super.noSuchMethod(
        Invocation.method(
          #getWalletSummary,
          [],
        ),
        returnValue:
            _i5.Future<_i3.WalletSummaryDto>.value(_FakeWalletSummaryDto_1(
          this,
          Invocation.method(
            #getWalletSummary,
            [],
          ),
        )),
      ) as _i5.Future<_i3.WalletSummaryDto>);

  @override
  _i5.Future<List<_i7.TransactionDto>> getWalletTransactions({
    int? page = 1,
    int? pageSize = 20,
    String? startDate,
    String? endDate,
    String? transactionType = 'all',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWalletTransactions,
          [],
          {
            #page: page,
            #pageSize: pageSize,
            #startDate: startDate,
            #endDate: endDate,
            #transactionType: transactionType,
          },
        ),
        returnValue:
            _i5.Future<List<_i7.TransactionDto>>.value(<_i7.TransactionDto>[]),
      ) as _i5.Future<List<_i7.TransactionDto>>);

  @override
  _i5.Future<List<_i8.SavedItemDto>> getSavedItems({
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSavedItems,
          [],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i5.Future<List<_i8.SavedItemDto>>.value(<_i8.SavedItemDto>[]),
      ) as _i5.Future<List<_i8.SavedItemDto>>);

  @override
  _i5.Future<List<_i9.LikedStoryDto>> getLikedStories({
    int? page = 1,
    int? pageSize = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLikedStories,
          [],
          {
            #page: page,
            #pageSize: pageSize,
          },
        ),
        returnValue:
            _i5.Future<List<_i9.LikedStoryDto>>.value(<_i9.LikedStoryDto>[]),
      ) as _i5.Future<List<_i9.LikedStoryDto>>);
}

/// A class which mocks [ProfileLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileLocalDataSource extends _i1.Mock
    implements _i10.ProfileLocalDataSource {
  MockProfileLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserProfileDto> getLastUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getLastUserProfile,
          [],
        ),
        returnValue: _i5.Future<_i2.UserProfileDto>.value(_FakeUserProfileDto_0(
          this,
          Invocation.method(
            #getLastUserProfile,
            [],
          ),
        )),
      ) as _i5.Future<_i2.UserProfileDto>);

  @override
  _i5.Future<void> cacheUserProfile(_i2.UserProfileDto? userProfile) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheUserProfile,
          [userProfile],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #clearUserProfile,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i11.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
