// Mocks generated by Mockito 5.4.5 from annotations
// in dskk_flutter_refactor/test/features/auth/data/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dskk_flutter_refactor/core/error/failures.dart' as _i8;
import 'package:dskk_flutter_refactor/core/network/network_info.dart' as _i11;
import 'package:dskk_flutter_refactor/core/platform/token_validator.dart'
    as _i12;
import 'package:dskk_flutter_refactor/core/storage/secure_storage_repository.dart'
    as _i10;
import 'package:dskk_flutter_refactor/features/auth/data/datasources/auth_remote_data_source.dart'
    as _i4;
import 'package:dskk_flutter_refactor/features/auth/data/models/authenticated_user_model.dart'
    as _i2;
import 'package:dskk_flutter_refactor/features/auth/domain/entities/auth_credentials.dart'
    as _i6;
import 'package:dskk_flutter_refactor/features/auth/domain/entities/user_info.dart'
    as _i9;
import 'package:dskk_flutter_refactor/features/auth/domain/repositories/i_user_info_repository.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthenticatedUserModel_0 extends _i1.SmartFake
    implements _i2.AuthenticatedUserModel {
  _FakeAuthenticatedUserModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i4.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.AuthenticatedUserModel> loginWithVerificationCode(
          _i6.VerificationCodeCredentials? credentials) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithVerificationCode,
          [credentials],
        ),
        returnValue: _i5.Future<_i2.AuthenticatedUserModel>.value(
            _FakeAuthenticatedUserModel_0(
          this,
          Invocation.method(
            #loginWithVerificationCode,
            [credentials],
          ),
        )),
      ) as _i5.Future<_i2.AuthenticatedUserModel>);

  @override
  _i5.Future<void> sendVerificationCode({required String? phone}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendVerificationCode,
          [],
          {#phone: phone},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [IUserInfoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserInfoRepository extends _i1.Mock
    implements _i7.IUserInfoRepository {
  MockIUserInfoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Either<_i8.Failure, _i9.UserInfo>> fetchUserInfo(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUserInfo,
          [token],
        ),
        returnValue: _i5.Future<_i3.Either<_i8.Failure, _i9.UserInfo>>.value(
            _FakeEither_1<_i8.Failure, _i9.UserInfo>(
          this,
          Invocation.method(
            #fetchUserInfo,
            [token],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i8.Failure, _i9.UserInfo>>);
}

/// A class which mocks [ISecureStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockISecureStorageRepository extends _i1.Mock
    implements _i10.ISecureStorageRepository {
  MockISecureStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String?> getString(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> saveString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int?> getInt(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [key],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<void> saveInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> saveToken(String? token) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [token],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteToken() => (super.noSuchMethod(
        Invocation.method(
          #deleteToken,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int?> getUserId() => (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<void> saveUserId(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #saveUserId,
          [userId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteUserId() => (super.noSuchMethod(
        Invocation.method(
          #deleteUserId,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int?> getCommonUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCommonUserId,
          [],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<void> saveCommonUserId(int? commonUserId) => (super.noSuchMethod(
        Invocation.method(
          #saveCommonUserId,
          [commonUserId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteCommonUserId() => (super.noSuchMethod(
        Invocation.method(
          #deleteCommonUserId,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllAuthData() => (super.noSuchMethod(
        Invocation.method(
          #clearAllAuthData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i11.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [TokenValidator].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenValidator extends _i1.Mock implements _i12.TokenValidator {
  MockTokenValidator() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i12.TokenValidationResult> validateToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateToken,
          [token],
        ),
        returnValue: _i5.Future<_i12.TokenValidationResult>.value(
            _i12.TokenValidationResult.valid),
      ) as _i5.Future<_i12.TokenValidationResult>);
}
