# Kotlin版本设置
kotlin.version=1.9.24
kotlinVersion=1.9.24
android.kotlinVersion=1.9.24

# KSP版本设置
kspVersion=1.9.24-1.0.20

# 抑制Kotlin版本兼容性检查
android.suppressKotlinVersionCompatibilityCheck=true
compose.kotlin.compiler.suppressKotlinVersionCompatibilityCheck=true

# 设置Compose编译器版本
compose.compiler.version=1.5.4