// Mocks generated by Mockito 5.4.5 from annotations
// in dskk_flutter_refactor/test/features/profile/presentation/bloc/profile_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dartz/dartz.dart' as _i3;
import 'package:dskk_flutter_refactor/core/error/failures.dart' as _i8;
import 'package:dskk_flutter_refactor/core/usecases/usecase.dart' as _i10;
import 'package:dskk_flutter_refactor/features/auth/domain/repositories/i_auth_repository.dart'
    as _i5;
import 'package:dskk_flutter_refactor/features/profile/domain/entities/user_profile.dart'
    as _i9;
import 'package:dskk_flutter_refactor/features/profile/domain/entities/wallet_summary.dart'
    as _i14;
import 'package:dskk_flutter_refactor/features/profile/domain/repositories/i_user_profile_repository.dart'
    as _i2;
import 'package:dskk_flutter_refactor/features/profile/domain/repositories/i_wallet_repository.dart'
    as _i4;
import 'package:dskk_flutter_refactor/features/profile/domain/usecases/check_auth_status.dart'
    as _i15;
import 'package:dskk_flutter_refactor/features/profile/domain/usecases/get_user_profile.dart'
    as _i6;
import 'package:dskk_flutter_refactor/features/profile/domain/usecases/get_wallet_summary.dart'
    as _i13;
import 'package:dskk_flutter_refactor/features/profile/domain/usecases/logout.dart'
    as _i16;
import 'package:dskk_flutter_refactor/features/profile/domain/usecases/update_user_profile.dart'
    as _i11;
import 'package:dskk_flutter_refactor/features/profile/domain/usecases/upload_avatar.dart'
    as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeIUserProfileRepository_0 extends _i1.SmartFake
    implements _i2.IUserProfileRepository {
  _FakeIUserProfileRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIWalletRepository_2 extends _i1.SmartFake
    implements _i4.IWalletRepository {
  _FakeIWalletRepository_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIAuthRepository_3 extends _i1.SmartFake
    implements _i5.IAuthRepository {
  _FakeIAuthRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetUserProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserProfileUseCase extends _i1.Mock
    implements _i6.GetUserProfileUseCase {
  MockGetUserProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IUserProfileRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeIUserProfileRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.IUserProfileRepository);

  @override
  _i7.Future<_i3.Either<_i8.Failure, _i9.UserProfile>> call(
          _i10.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, _i9.UserProfile>>.value(
            _FakeEither_1<_i8.Failure, _i9.UserProfile>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, _i9.UserProfile>>);
}

/// A class which mocks [UpdateUserProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserProfileUseCase extends _i1.Mock
    implements _i11.UpdateUserProfileUseCase {
  MockUpdateUserProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IUserProfileRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeIUserProfileRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.IUserProfileRepository);

  @override
  _i7.Future<_i3.Either<_i8.Failure, _i9.UserProfile>> call(
          _i11.UpdateUserProfileParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, _i9.UserProfile>>.value(
            _FakeEither_1<_i8.Failure, _i9.UserProfile>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, _i9.UserProfile>>);
}

/// A class which mocks [UploadAvatarUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUploadAvatarUseCase extends _i1.Mock
    implements _i12.UploadAvatarUseCase {
  MockUploadAvatarUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.IUserProfileRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeIUserProfileRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.IUserProfileRepository);

  @override
  _i7.Future<_i3.Either<_i8.Failure, String>> call(
          _i12.UploadAvatarParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, String>>.value(
            _FakeEither_1<_i8.Failure, String>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, String>>);
}

/// A class which mocks [GetWalletSummary].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWalletSummary extends _i1.Mock implements _i13.GetWalletSummary {
  MockGetWalletSummary() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.IWalletRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeIWalletRepository_2(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i4.IWalletRepository);

  @override
  _i7.Future<_i3.Either<_i8.Failure, _i14.WalletSummary>> call(
          _i10.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i7.Future<_i3.Either<_i8.Failure, _i14.WalletSummary>>.value(
                _FakeEither_1<_i8.Failure, _i14.WalletSummary>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, _i14.WalletSummary>>);
}

/// A class which mocks [CheckAuthStatusUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCheckAuthStatusUseCase extends _i1.Mock
    implements _i15.CheckAuthStatusUseCase {
  MockCheckAuthStatusUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.IAuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeIAuthRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.IAuthRepository);

  @override
  _i7.Future<_i3.Either<_i8.Failure, bool>> call(_i10.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, bool>>.value(
            _FakeEither_1<_i8.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, bool>>);
}

/// A class which mocks [LogoutUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUseCase extends _i1.Mock implements _i16.LogoutUseCase {
  MockLogoutUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.IAuthRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeIAuthRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.IAuthRepository);

  @override
  _i7.Future<_i3.Either<_i8.Failure, void>> call(_i10.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i7.Future<_i3.Either<_i8.Failure, void>>.value(
            _FakeEither_1<_i8.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i7.Future<_i3.Either<_i8.Failure, void>>);
}
