import 'package:equatable/equatable.dart';

/// Represents the role of the message sender (user or AI assistant).
enum MessageRole { user, assistant }

/// {@template ai_chat_message}
/// Represents a single message within an AI chat conversation.
///
/// Corresponds to the data structure returned by the `/model/chat/messages` API
/// and used in the `chatBotSlice` state.
/// {@endtemplate}
class AIChatMessage extends Equatable {
  /// {@macro ai_chat_message}
  const AIChatMessage({
    this.id, // Assuming ID might be assigned by DB later
    required this.messageId, // Unique ID generated by backend or frontend?
    required this.conversationId,
    required this.role,
    required this.content,
    this.files = const [], // List of OSS URLs (or potentially local URIs before upload?)
    this.timestamp,
  });

  /// Optional database ID.
  final int? id;

  /// A unique identifier for the message (e.g., generated timestamp or backend ID).
  final String messageId;

  /// The ID of the conversation this message belongs to.
  final int conversationId;

  /// The role of the message sender.
  final MessageRole role;

  /// The textual content of the message.
  final String content;

  /// List of file URLs (阿里云 OSS URLs) associated with the message.
  /// Note: Before upload, this might contain local file URIs in some implementations.
  final List<String> files;

  /// Timestamp when the message was created or received.
  final DateTime? timestamp;

  @override
  List<Object?> get props => [
        id,
        messageId,
        conversationId,
        role,
        content,
        files,
        timestamp,
      ];

  /// Creates a copy of this [AIChatMessage] but with the given fields replaced with
  /// the new values.
  AIChatMessage copyWith({
    int? id,
    String? messageId,
    int? conversationId,
    MessageRole? role,
    String? content,
    List<String>? files,
    DateTime? timestamp,
  }) {
    return AIChatMessage(
      id: id ?? this.id,
      messageId: messageId ?? this.messageId,
      conversationId: conversationId ?? this.conversationId,
      role: role ?? this.role,
      content: content ?? this.content,
      files: files ?? this.files,
      timestamp: timestamp ?? this.timestamp,
    );
  }
} 