// Mocks generated by Mockito 5.4.5 from annotations
// in dskk_flutter_refactor/test/features/auth/domain/usecases/login_with_verification_code_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dskk_flutter_refactor/core/error/failures.dart' as _i6;
import 'package:dskk_flutter_refactor/features/auth/domain/entities/auth_credentials.dart'
    as _i8;
import 'package:dskk_flutter_refactor/features/auth/domain/entities/auth_status.dart'
    as _i5;
import 'package:dskk_flutter_refactor/features/auth/domain/entities/authenticated_user.dart'
    as _i7;
import 'package:dskk_flutter_refactor/features/auth/domain/repositories/i_auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i3.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.AuthStatus> get authStatus => (super.noSuchMethod(
        Invocation.getter(#authStatus),
        returnValue: _i4.Stream<_i5.AuthStatus>.empty(),
      ) as _i4.Stream<_i5.AuthStatus>);

  @override
  _i4.Future<
      _i2.Either<_i6.Failure, _i7.AuthenticatedUser>> loginWithVerificationCode(
          _i8.VerificationCodeCredentials? credentials) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginWithVerificationCode,
          [credentials],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.Failure, _i7.AuthenticatedUser>>.value(
                _FakeEither_0<_i6.Failure, _i7.AuthenticatedUser>(
          this,
          Invocation.method(
            #loginWithVerificationCode,
            [credentials],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, _i7.AuthenticatedUser>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #logout,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> sendVerificationCode(
          {required String? phone}) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendVerificationCode,
          [],
          {#phone: phone},
        ),
        returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
            _FakeEither_0<_i6.Failure, void>(
          this,
          Invocation.method(
            #sendVerificationCode,
            [],
            {#phone: phone},
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i2.Either<_i6.Failure, _i7.AuthenticatedUser?> getLoggedInUserSync() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLoggedInUserSync,
          [],
        ),
        returnValue: _FakeEither_0<_i6.Failure, _i7.AuthenticatedUser?>(
          this,
          Invocation.method(
            #getLoggedInUserSync,
            [],
          ),
        ),
      ) as _i2.Either<_i6.Failure, _i7.AuthenticatedUser?>);
}
